- name: Create Neutron DB
  mysql_db:
    name: neutron
    state: present

- name: Update mysql neutron password for all glance accounts
  no_log: false
  mysql_user:
     name: neutron
     host: "{{ item }}"
     plugin: caching_sha2_password
     plugin_auth_string: "{{ db_password }}"
     priv: neutron.*:ALL,GRANT
     state: present
     update_password: on_create
  with_items:
     - localhost
     - "{{ internal_vip_address.split('.')[:3] | join('.') + '.%' }}" 
