- name: Neutron User Create
  openstack.cloud.identity_user:
    cloud: "{{ cloud }}"
    state: present
    name: neutron
    password: "{{ keystone_pass }}"
    domain: default
    interface: internal
    default_project: service

- name: Neutron user role assignment 
  openstack.cloud.role_assignment:
    cloud: "{{ cloud }}"
    user: neutron
    role: admin
    project: service
    interface: internal

- name: Neutron user role assignment service
  openstack.cloud.role_assignment:
    cloud: "{{ cloud }}"
    user: neutron
    role: service
    project: service
    interface: internal

- name: Create Service Project
  openstack.cloud.catalog_service:
    cloud: "{{ cloud }}"
    state: present
    name: neutron
    description: Contrabass Networking
    enabled: True
    service_type: network
    interface: internal

- name: Neutron endpoint create
  openstack.cloud.endpoint:
    cloud: "{{ cloud }}"
    service: neutron
    endpoint_interface: "{{ item.interface }}"
    url: "{{ item.interface_protocol }}://{{ item.endpoint }}:{{ neutron_bind_port }}"
    region: RegionOne
    state: present
    interface: internal
  with_items:
    - { interface: "internal", interface_protocol: "{{ internal_endpoint_protocol }}", endpoint: "{{ internal_endpoint }}" }
    - { interface: "admin", interface_protocol: "{{ internal_endpoint_protocol }}", endpoint: "{{ admin_endpoint }}" }
    - { interface: "public", interface_protocol: "{{ public_endpoint_protocol }}", endpoint: "{{ public_endpoint }}" }
