version: '3'

services:
  ################################## vault-init #######################################
  vault-init:
    container_name: vault-init
    image: localhost:5555/vault:1.14.1
    privileged: true
    volumes:
      - vault-data:/vault/data:z
      - ./config/vault/init.sh:/usr/local/bin/init.sh
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_API_ADDR: http://vault:8200
    command: 
      - /usr/local/bin/init.sh
    networks:
      - maestro
    restart: always
volumes:
  vault-data:
    driver: local
networks:
  maestro:
    driver: bridge
    external: true
