- name: Create corosync log directory
  ansible.builtin.file:
    path: /var/log/corosync
    state: directory
    owner: root
    group: root
    mode: '0755'
  when:
    - ansible_os_family == "RedHat"

- name: corosync conf copy
  template:
    src: "{{ corosync_config }}.j2"
    dest: "{{ corosync_config_dir }}/{{ corosync_config }}"
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_os_family == "RedHat"

- name: corosync service restart
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - corosync
  when:
    - ansible_os_family == "RedHat"
