- name: Crete mole directory for mole files
  file:
    path: "{{ mole_install_dir }}" 
    state: directory
    mode: 0755
    owner: root
    group: root

- name: check mole file exists
  stat:
    path: "{{ mole_install_dir }}/{{ mole_tar_file }}"
  register: mole_tar

- name: check mole installer exists
  stat:
    path: "{{ mole_install_dir }}/{{ mole_installer }}"
  register: mole_inst

- name: Copy mole files
  copy:
    src: "{{ mole_tar_file }}"
    dest: "{{ mole_install_dir }}/{{ mole_tar_file }}"
    mode: 0644
    owner: root
    group: root
  when: not mole_tar.stat.exists

- name: Copy mole installer
  copy:
    src: "{{ mole_installer }}"
    dest: "{{ mole_install_dir }}/{{ mole_installer }}"
    mode: 0755
    owner: root
    group: root
  when: not mole_inst.stat.exists

- name: Check contrabass-mole service file exists
  stat:
    path: /etc/systemd/system/contrabass-mole.service
  register: mole_service

- name: Install contrabass-mole compute nodes
  shell: "{{ mole_install_dir }}/contrabass-mole-install.sh compute"
  args:
    chdir: "{{ mole_install_dir }}"
  when:
    - not mole_service.stat.exists
    - inventory_hostname in groups['compute']

- name: Install contrabass-mole controller
  shell: "{{ mole_install_dir }}/contrabass-mole-install.sh control"
  args:
    chdir: "{{ mole_install_dir }}"
  when:
    - not mole_service.stat.exists
    - inventory_hostname in groups['controller'] and inventory_hostname not in groups['compute']

- name: Set ownership of mole_install_dir to root:root
  file:
    path: "{{ mole_install_dir }}"
    owner: root
    group: root
    recurse: yes
