#baremetal inventory#
[alls]
# ex)hcon01 ansible_host=172.18.0.101 ansible_user=root
# ex)compute01 ansible_host=172.19.0.102 ansible_user=root
hcon01 ansible_host=10.255.191.151 ansible_user=root
hcon02 ansible_host=10.255.191.152 ansible_user=root
hcon03 ansible_host=10.255.191.153 ansible_user=root
hcom01 ansible_host=10.255.191.154 ansible_user=root
hcom02 ansible_host=10.255.191.155 ansible_user=root

deploy ansible_host=localhost ansible_user=root

#[alls:vars]
#ansible_python_interpreter=/usr/bin/python3

[openstack]
hcon01
hcon02
hcon03
hcom01
hcom02

[controller]
hcon01
hcon02
hcon03

[compute]
hcom01
hcom02
#hcon03

[neutron_agent]
hcon01
hcon02
hcon03

[storage]
hcon01
hcon02
hcon03

[deploy]
deploy

[new-compute]

[mons]

[osds]

[rgws]

[mdss]

[gpu]


#########BEGIN Purge Section##########
[purgecluster:children]
purge-compute
purge-controller

[purge-compute]

[purge-controller]

#########FINISH Purge Section#########

