# Run memcached as a daemon
-d

# Separate log file for Thanos cache instance.
logfile /var/log/memcached-thanos.log

# Memory for Thanos Query Frontend response cache.
-m "4096"

# Thanos dedicated memcached port.
-p "11212"

# Run as package-provided memcache user.
-u memcache

# Bind only to controller internal IP.
# Replace this per controller.
-l 0.0.0.0

# Max simultaneous incoming connections.
-c "4096"

# Separate PID file.
-P /run/memcached/memcached-thanos.pid

-I 8m

