---
- name: Create PDNS DB
  mysql_db:
    name: pdns
    state: present

- name: Update mysql PDNS password for all PDNS accounts
  mysql_user:
    name: pdns
    host: "{{ item }}"
    password: "{{ db_password }}"
    priv: pdns.*:ALL,GRANT
    state: present
  with_items:
    - localhost
    - '%'
    - "{{ internal_vip_address }}"

