---
- name: Copy Repository configuration files Ubuntu
  become: true
  template:
    src: "{{ repo_file }}.j2"
    dest: "{{ repo_dir }}/{{ repo_file }}"
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian" 

- name: copy gpg_key Ubuntu
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ repo_key_dir }}"
    owner: root
    group: root
    mode: 0644
  with_items:
   - percona-keyring.gpg
   - ubuntu-keyring-2012-cloud-archive.gpg
   - maas_ubuntu_3_2.gpg
   - com.rabbitmq.team.gpg
  when: ansible_os_family == "Debian"

- name: Remove source list file
  file:
    path: '/etc/apt/sources.list.d/ubuntu.sources'
    state: absent

- name: apt update && upgrade
  become: true
  apt:
    update_cache: false
    force_apt_get: false
  when: ansible_os_family == "Debian"

- name: Pakage installation Ubuntu
  apt:
    update_cache: false
    name:
      - aptitude
      - curl
      - telnet
      - tree
      - tcpdump 
      - iperf3       
      - net-tools
      - network-manager
      - snmp
      - snmpd
      - lldpd
      - ipmitool
      - freeipmi
      - sysfsutils
    state: present
  when: ansible_os_family == "Debian"

- name: Stop & Disable Service Ubuntu
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - apparmor 
    - ufw
    - unattended-upgrades
    - apt-daily
    - apt-daily.timer
    - apt-daily-upgrade
    - apt-daily-upgrade.timer
  when: ansible_os_family == "Debian"

- block:
    - name: Package installation Ubuntu
      apt:
        update_cache: false
        name: python3-pip
        state: present

    - name: copy oslo.messaging wheel to remote
      ansible.builtin.copy:
        src: oslo.messaging-14.7.2-py3-none-any.whl
        dest: /tmp/
        owner: root
        group: root
        mode: '0644'

    - name: install oslo.messaging
      ansible.builtin.pip:
        name: "oslo.messaging==14.7.2"
        extra_args: >-
          --break-system-packages
          --no-index
          --no-deps
          --find-links /tmp/
        state: present

    - name: Remove oslo.messaging wheel file
      ansible.builtin.file:
        path: /tmp/oslo.messaging-14.7.2-py3-none-any.whl
        state: absent

  when: openstack_version == 'caracal'
