---
- name: Copy Thanos query service file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'thanos-query.service.j2',dest: '{{ thanos_service_daemon_path }}/thanos-query.service',owner: 'root',group: 'root',mode: '0644' }

- name: Reload Daemon
  shell: systemctl daemon-reload

- name: Start Thanos query service
  service:
    name: thanos-query
    state: restarted
    enabled: true

- name: Configure monitoring Thanos query to haproxy.cfg
  blockinfile:
    path: "{{ haproxy_dir }}/{{ haproxy_file }}"
    marker: "## {mark} monitoring_thanos_query ##"
    insertbefore: EOF
    block: |
      listen int_thanos_query
        bind {{ monitoring_vip_address }}:{{ thanos_query_http_loadbalance_port }} {% if monitoring_enable_tls %}ssl crt {{ monitoring_certs_dir }}/monitoring-server.pem ssl verify none{% endif %}

        balance  source
        option tcpka
        option httpchk
        option tcplog
      {% for item in groups['controller'] %}
        server {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_'~monitoring_network_interface].ipv4.address }}:{{ thanos_query_http_port }} check inter 2000 rise 2 fall 5 {% if monitoring_enable_tls %}ssl crt {{ monitoring_certs_dir }}/monitoring-server.pem ssl verify none{% endif %}

      {% endfor %}

- name: Restart HAProxy service
  service:
    name: haproxy
    state: restarted
  ignore_errors: true
