---
- name: Copy Contrabass-exporter binary file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: '/root/okestro/okestro-openstack/roles/prometheus/files/contrabass-exporter',dest: '{{ exe_path }}',owner: 'root',group: 'root',mode: '0755' }

- name: Copy Contrabass-exporter service file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'contrabass-exporter.service.j2',dest: '{{ contrabass_exporter_service_daemon_path }}/contrabass-exporter.service',owner: 'root',group: 'root',mode: '0644' }

- name: Reload Daemon
  shell: systemctl daemon-reload

- name: Start Contrabass-exporter service
  service:
    name: contrabass-exporter
    state: restarted
    enabled: true
