---
- name: Copy libvirt config file
  template:
    src: "{{ libvirt_config }}.j2"
    dest: "{{ libvirt_dir }}/{{ libvirt_config }}"
    owner: root
    group: libvirt
    mode: 0644
    backup: true

- name: Copy qemu config file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0644
  with_items:
    - { src: 'qemu.conf',dest: '/etc/libvirt/qemu.conf', owner: 'root',group: 'libvirt' }
  when:
    - enable_openstack_tls == true

- name: Stop nova-compute for libvirt-tls.socket enable
  service:
    name: "{{ pac_nova_compute }}"
    state: stopped

- name: Stop Libvirtd daemon and enable live migration socket
  service:
    name: "{{ item.service }}"
    state: "{{ item.state }}"
    enabled: yes
  with_items:
    - { service: 'libvirtd', state: stopped }
    - { service: "{{ 'libvirtd-tls.socket' if enable_openstack_tls else 'libvirtd-tcp.socket' }}", state: started }

- name: Start libvirtd daemon
  service:
    name: 'libvirtd'
    state: started
    enabled: yes

- name: Restart nova-compute
  service:
    name: "{{ pac_nova_compute }}"
    state: restarted

- name: Change Nova User Bash Shell
  shell: usermod -s /bin/bash nova

- name: Create Nova ssh Dir
  file:
    path: /var/lib/nova/.ssh
    state: directory
    owner: nova
    group: nova

- name: Copy Nova SSH Files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: nova
    group: nova
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'id_rsa',dest: '/var/lib/nova/.ssh/id_rsa',mode: '0600' }
    - { src: 'id_rsa.pub',dest: '/var/lib/nova/.ssh/id_rsa.pub',mode: '0644' }
    - { src: 'config',dest: '/var/lib/nova/.ssh/config',mode: '0644' }
    - { src: 'authorized_keys',dest: '/var/lib/nova/.ssh/authorized_keys',mode: '0644' }
