---
- name: Compute Service restart
  service: 
    name: "{{ item }}"
    state: restarted
  with_items: 
    - "{{ pac_nova_compute }}"
    - neutron-openvswitch-agent

- name: Neutron Service Restart
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-metadata-agent
  when: inventory_hostname in groups['neutron_agent']
