- name: external bridge create
  openvswitch.openvswitch.openvswitch_bridge:
    bridge: "{{ item.bridge }}"
    state: present
    fail_mode: secure
  loop: "{{ bridges }}"

- name: external bridge port mapping
  openvswitch.openvswitch.openvswitch_port:
    bridge: "{{ item.bridge }}"
    port: "{{ item.port }}"
    state: present
    tag: "{{ item.vlan | default(omit) }}"
  loop: "{{ bridges }}"
