---
- name: Stop all instances
  service:
    name: mysql
    state: stopped

- name: Create MySQL log directory on RedHat
  ansible.builtin.file:
    path: /var/log/mysql
    state: directory
    owner: mysql
    group: adm
    mode: '0755'
  when: ansible_os_family == "RedHat"

- name: Configure mysql configuration
  template:
    src: percona-xtradb-cluster.cnf.j2
    dest: "{{ mysql_config }}"
    owner: 'mysql'
    group: 'mysql'
    mode: '0640'

- name: Configure Percona to haproxy.cfg
  blockinfile:
    path: "{{ haproxy_dir }}/{{ haproxy_file }}"
    marker: "## {mark} Percona_XtraDB_Cluster ##"
    insertbefore: "# public"
    block: |
      listen int_percona_cluster
        bind {{ internal_vip_address }}:{{ percona_bind_port }}

        balance  source
        mode tcp
        option tcpka
        option tcplog

        option redispatch
        retries 3
        maxconn 20000
        timeout connect 10s
        timeout server 10800s
        timeout client 10800s
        default-server inter 2000 rise 2 fall 3 on-marked-down shutdown-sessions

        server {{ hostvars[groups['controller'][0]]['ansible_hostname'] }} {{ hostvars[groups['controller'][0]]['ansible_' + int_api_interface].ipv4.address }}:{{ percona_port }} check
      {% for item in groups['controller'][1:] %}
        server {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_' + int_api_interface].ipv4.address }}:{{ percona_port }} check backup
      {% endfor %}
  register: percona_int_haproxy

- name: Restart Haproxy
  service:
    name: haproxy
    state: restarted
  when: percona_int_haproxy.changed
