---
- name: Register Mysql Module
  shell: dnf module list | grep mysql | grep 'x'
  register: mysql_module
  when: ansible_os_family == "RedHat"
  ignore_errors: true

- name: Disable mysql module dnf
  command: dnf module disable mysql -y
  when: 
    - ansible_os_family == "RedHat"
    - mysql_module.rc != 0
    - ansible_facts['distribution_major_version'] is version('9','<')

- name: install percona-xtradb-cluster-8 Ubuntu
  ansible.builtin.package:
    name:
       - "{{ pac_percona_cluster }}" 
       - "{{ pac_percona_mysqldb }}"
       - "{{ pac_percona_pymysql }}"
       - "{{ pac_percona_xtrabackup }}"
    state: present

- name: register .my.cnf
  stat:
    path: /root/.my.cnf
  register: mysql_conf
  when: ansible_os_family == "RedHat"

- name: start mysql for password setting RedHat
  service:
    name: mysql
    state: started
  when: 
    - ansible_os_family == "RedHat"
    - not mysql_conf.stat.exists

- name: copy password setting script
  template:
    src: "password.sh.j2"
    dest: /root/password.sh
    owner: root
    group: root
    mode: 0755
  when: 
    - ansible_os_family == "RedHat"
    - not mysql_conf.stat.exists

- name: password setting
  shell: ./password.sh
  args:
    chdir: /root
  when: 
    - ansible_os_family == "RedHat"
    - not mysql_conf.stat.exists

- name: remove passowrd setting files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /root/password.sh
  when: 
    - ansible_os_family == "RedHat"
    - not mysql_conf.stat.exists

- name: stop mysql for end password setting
  service:
    name: mysql
    state: stopped
  when: 
    - ansible_os_family == "RedHat"
    - not mysql_conf.stat.exists

- name: copy my.cnf file
  template:
    src: "my.cnf.j2"
    dest: .my.cnf
    owner: root
    group: root
    mode: 0600
