- block:
    - name: validate_password component install check
      community.mysql.mysql_query:
        query: "SELECT component_urn FROM mysql.component WHERE component_urn = 'file://component_validate_password'"
        login_unix_socket: "{{ mysql_unix_socket }}"
        login_user: root
        login_password: "{{ db_password }}"
      register: validate_password_component_check
      changed_when: false
    
    - name: validate_password component install
      community.mysql.mysql_query:
        query: "INSTALL COMPONENT 'file://component_validate_password'"
        login_unix_socket: "{{ mysql_unix_socket }}"
        login_user: root
        login_password: "{{ db_password }}"
      when: validate_password_component_check.rowcount[0] == 0
    
    - name: set validate_password
      community.mysql.mysql_variables:
        variable: "{{ item.key }}"
        value: "{{ item.value }}"
        login_unix_socket: "{{ mysql_unix_socket }}"
        login_user: root
        login_password: "{{ db_password }}"
      loop:
        - { key: "validate_password.policy", value: "MEDIUM" }
        - { key: "validate_password.length", value: "8" }
        - { key: "validate_password.mixed_case_count", value: "1" }
        - { key: "validate_password.number_count", value: "1" }
        - { key: "validate_password.special_char_count", value: "1" }
      loop_control:
        label: "{{ item.key }}"
  when: inventory_hostname == groups['controller'][0]

- name: Add validate_password settings 
  ansible.builtin.lineinfile:
    path: "{{ mysql_config }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
    state: present
  loop:
    - { line: "validate_password.length=8",                    insertafter: "^default_authentication_plugin=caching_sha2_password" }
    - { line: "validate_password.mixed_case_count=1",           insertafter: "^validate_password.length=8" }
    - { line: "validate_password.number_count=1",               insertafter: "^validate_password.mixed_case_count=1" }
    - { line: "validate_password.special_char_count=1",         insertafter: "^validate_password.number_count=1" }
    - { line: "validate_password.policy=MEDIUM",                insertafter: "^validate_password.special_char_count=1" }
  loop_control:
    label: "{{ item.line }}"

