OCTAVIA_MGMT_SUBNET: 172.16.0.0/22
OCTAVIA_MGMT_SUBNET_START: 172.16.0.100
OCTAVIA_MGMT_SUBNET_END: 172.16.2.254
OCTAVIA_MGMT_PORT_IP: 172.16.0.2
OCTAVIA_NETWORK_NAME: lb-mgmt-net
OCTAVIA_MGMT_SUBNET_NAME: lb-mgmt-subnet
